permalink: /:categories/:title/
url: "http://example.com"
full_name: "Сделано с &#128156;"
first_name: "Аниме Космос"
last_name: "/images/users/f.png"
blog_title: "Аниме Космос"
author_img_name_path: "/images/users/f.png"
disqus_shortname: "example"
copyright_year: "2019"
google_analytics_code: ""
aboutme: "I like ramen noodles with cream."
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
paginate: 9
breadcrumbs:
  root:
    hide: true  # show breadcrumbs on root/home page
    image: true # Show image or title text